services:
  - type: web
    name: telegram-sub2unlock-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
