services:
  - type: web
    name: telegram-sub2unlock-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python sub2unlock.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
